# Generated by Django 4.2.13 on 2024-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
