# Generated by Django 4.2.13 on 2024-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0004_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
