# Generated by Django 4.2.13 on 2024-06-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0005_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
