# Generated by Django 4.2.13 on 2025-03-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0006_alter_contact_address_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_images/'),
        ),
    ]
