# Generated by Django 4.2.13 on 2025-03-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0007_contact_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
