# Generated by Django 4.2.13 on 2025-03-09 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_app', '0008_remove_contact_image'),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_app.contact')),
                ('products', models.ManyToManyField(to='product_app.product')),
            ],
        ),
    ]
