# Generated by Django 4.2.13 on 2025-03-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytransaction',
            name='products',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='products',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
            preserve_default=False,
        ),
    ]
