# Generated by Django 4.2.13 on 2025-03-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventorytransaction_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
