# Generated by Django 4.2.13 on 2025-03-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorytransaction_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
